### ISSUE TITLE
Text too dark in States and in HACS

### ISSUE THREAD

**Issue by atomicpapa** [bbbenji/synthwave-hass#11]
In Developer Tools > States the entities are way too dark

and in HACS the links for "Upgrade", "Repository", etc on detail screen for any specific item appear to match the background color.

**Comment by niemyjski** [comment]
@atomicpapa not to take over this issue... how do you even get this working in HACS? I've clicked install, added code to configuration and I can't set any theme.. It's grayed out in the ui

**Comment by bbbenji** [comment]
@niemyjski did you install `synthwave-hass` or `synthwave-hass-extras`? The latter is optional, the first is the actual theme. Once you have it installed you can enable it from your profile page.

Also, this is off-topic, please create a new issue next time.

**Comment by flexage** [comment]
I too had noticed the entity links on the `Developer Tools > States` and the link on the HACS store were too dark.

It seems that Home Assistant is using the `--primary-color` css variable, and we actually want it to pull the `dark-primary-color` or `accent-color` vaiable.

I tried to find some CSS reference for the HA Developer Tools but couldn't turn anything up with a quick search on google and through the HA Polymer repo.

HACS on the other hand has some info for theming it - https://hacs.netlify.com/usage/theming/

I noticed none of the variables documented on that link are present on this theme.

Great work though, this theme is my daily driver 👍

**Comment by bbbenji** [comment]
@flexage Thanks! I will definitely take a look when I find a moment.

**Comment by cjd** [comment]
The issue may be that on those pages HA is using primary-background-color for the background and primary-color for the text/links - but in synthwave.yaml they are set to the same thing

**Comment by nutteloost** [comment]
This issue is holding me back from using this theme. Do you think this is gonna be fixed sometime?

**Comment by mandalarigabriele** [comment]
Any news about this issue?

**Comment by bbbenji** [comment]
Fixed via https://github.com/bbbenji/synthwave-hass-extras/pull/2
