### ISSUE TITLE
How to install this theme (Hassio + HACS)

### ISSUE THREAD

**Issue by niemyjski** [bbbenji/synthwave-hass#12]
I installed `synthwave-hass` and `synthwave-hass-extras` in the latest stable version of HACS running on 0.97.2. But I cannot for the life of me get any theme to show up. Do you know what I'm missing?

![image](https://user-images.githubusercontent.com/1020579/63588334-da878d80-c56b-11e9-9d10-f653790f7d36.png)

https://github.com/niemyjski/home-assistant/blob/master/config/frontend.yaml

![image](https://user-images.githubusercontent.com/1020579/63588571-74e7d100-c56c-11e9-8ce4-7ecccd28f035.png)

Calling the service to reload themes or set themes does not work. I have no freaking idea why this isn't showing up (and I haven't had time to dig through the code for HACS, this script or HA).

**Comment by bbbenji** [comment]
Your `configuration.yaml` is referencing `config/frontend.yaml` for `frontend` and `frontend.yaml` is referencing `themes`. Maybe it should be `../themes`?

Or just put `themes: !include_dir_merge_named themes` directly in `configuration.yaml`. It'll save you a line of code and a superfluous file.

**Comment by niemyjski** [comment]
I'll try that. I just got it from here: https://www.home-assistant.io/components/frontend/#themes

**Comment by niemyjski** [comment]
Sweet! That was the issue!!! Thanks again
