### ISSUE TITLE
Possible to theme scroll bar?

### ISSUE THREAD

**Issue by nphil** [bbbenji/synthwave-hass#15]
I apologize if this is a silly question - is it possible to theme or even hide the scroll bar on the side bar? See attached picture. Really takes away from an otherwise perfect theme!
<img width="279" alt="Screen Shot 2019-11-27 at 1 05 06 AM" src="https://user-images.githubusercontent.com/1761280/69697935-f55d2700-10b1-11ea-92fb-02e8ce4259bd.png">

**Comment by bbbenji** [comment]
I will look into this during some free time.

**Comment by bbbenji** [comment]
Closed via: https://github.com/bbbenji/synthwave-hass/pull/28
