### ISSUE TITLE
Gauge card

### ISSUE THREAD

**Issue by planet4** [bbbenji/synthwave-hass#17]
Thanks for sharing. Looks very good. I have some issues with gaugecard. I suppose this is because some transperency is used? The bottom of the gauge is dark green.

![gauge](https://user-images.githubusercontent.com/22392924/71898061-9da5e700-3158-11ea-9aad-f0685196724f.PNG)

**Comment by jamescadd** [comment]
This was an issue but appears fixed (for me) in the latest release.  Can this be closed?
