### ISSUE TITLE
Link colors in logbook and entity state viewer are illegible

### ISSUE THREAD

**Issue by ghost** [bbbenji/synthwave-hass#18]
The link colors are too dark, it appears this has been previously addressed however I am still seeing an issue.

Synthwave: Installed: 0.2.2
Home Assistant 0.104.2
HassOS 3.8
HACS Integration version: 0.20.8
Frontend version: 20200104192235

Thank you

![2020-01-18_024325](https://user-images.githubusercontent.com/128811/72662504-e5204480-399c-11ea-97c1-0ca124656cf0.png)
![2020-01-18_024418](https://user-images.githubusercontent.com/128811/72662505-e5204480-399c-11ea-84ef-0220ed1d33a3.png)

**Comment by bbbenji** [comment]
Are you running synthwave-hass-extras?

**Comment by ghost** [comment]
Thank you, I did not realize that was available. I will install that.
