### ISSUE TITLE
I really like this theme and I even create a video tutorial about it

### ISSUE THREAD

**Issue by peyanski** [bbbenji/synthwave-hass#19]
Hi there,

this is my video guide/tutorial - https://youtu.be/4cOdgW23KCA
If you think that the video is helpful you can put it somewhere in the README.md
Or I if it's easier for you I can do that and create a Pull request

Either way keep up the good work.
Cheers,
Kiril

**Comment by bbbenji** [comment]
I really enjoyed your video, however, this theme was only mentioned shortly at the very end and overall doesn't relate too much to Synthwave.

Having said that, I am happy to see videos like this helping people out with Home Assistant!
