### ISSUE TITLE
White wallpaper in media-control card

### ISSUE THREAD

**Issue by NeySlim** [bbbenji/synthwave-hass#24]
Since 0.23, the wallpaper of media control cards is white:
![image](https://user-images.githubusercontent.com/4509984/75982756-91839f00-5ee7-11ea-8214-2be65037db88.png)

Installed version: .024
![image](https://user-images.githubusercontent.com/4509984/75982833-b9730280-5ee7-11ea-8d10-58ae3a7fb11e.png)

Tested on Firefox and Edge chromium

**Comment by bbbenji** [comment]
You're right. I will try to look into this soon.

**Comment by fasm** [comment]
set the following
`primary-color: '#34294f88'`
save, restart HASS

**Comment by yavik-kapadia** [comment]
> set the following
> `primary-color: '#34294f88'`
> save, restart HASS

:< sorry I'm a noob but would I edit the theme file or the card with that line.

**Comment by fasm** [comment]
The yaml theme file. Look for the line referencing "primary-color" (line 9) and replace the value.

**Comment by CyanoFresh** [comment]
@fasm's proposed change fixes the issue
