### ISSUE TITLE
Default theme background while loading homeassistant

### ISSUE THREAD

**Issue by celeroncool** [bbbenji/synthwave-hass#25]
Hello!

Would it be possible to theme the Homeassistant loading screen too?

Currently, when you first load up homeassistant page or refresh page, you get a super bright white background with homeassistant blue top navbar, then the theme loads up.

So far, I have found the html file responsible for the white page, https://github.com/home-assistant/frontend/blob/master/src/html/index.html.template
Is there any change we could change the background color of this page too?

**Comment by bbbenji** [comment]
Not possible AFAIK. Closing until someone can verify otherwise.
