### ISSUE TITLE
What the card do you use for vacuum cleaner?

### ISSUE THREAD

**Issue by denysdovhan** [bbbenji/synthwave-hass#29]
Seems like you use custom card for the vacuum cleaner. Can you share a link for this card?

<img width="446" alt="Screenshot 2020-05-02 at 17 11 08" src="https://user-images.githubusercontent.com/3459374/80866546-f36a4600-8c97-11ea-907d-c360e4c8df1e.png">

**Comment by bbbenji** [comment]
Found the card here: https://macbury.github.io/SmartHouse/HomeAssistant/Vacuum/

I made a few changes to it in order to better fit the Synthwave theme, you can find that here: https://gist.github.com/bbbenji/24372e423f8669b2e6713638d8f8ceb2

**Comment by denysdovhan** [comment]
Thank you!

**Comment by denysdovhan** [comment]
@bbbenji I've built my custom card for vacuum based on the original one: https://github.com/denysdovhan/vacuum-card

I've sent your invite to contribute to the repo. We both might use it and improve it for our mutual benefit.

**Comment by bbbenji** [comment]
@denysdovhan awesome! I will be working on my HASS next month as we will be moving soon and will definitely look into your fork and see where I can contribute:) Thanks.
