### ISSUE TITLE
All icons are white :'( in 3.3

### ISSUE THREAD

**Issue by csacre** [bbbenji/synthwave-hass#31]
First, thank you sharing your work! 

After the update, all my icons are now "white" (eg lights turned on is not yellow anymore and remains white). I rolled back to 3.1

**Comment by iceman23e** [comment]
Same. I deleted the new entry `iron-icon-fill-color: '#fff'`, reloaded the theme and it's fixed.

**Comment by willpall7** [comment]
Same issue here. Thanks @iceman23e for the "patch" :)

**Comment by bbbenji** [comment]
Reverted the change: https://github.com/bbbenji/synthwave-hass/releases/tag/0.3.3.1

At the cost of this: 
![Screen Shot 2020-05-07 at 12 02 59 AM](https://user-images.githubusercontent.com/1678118/81232959-24c77680-8ff6-11ea-982c-e1572c2bf407.png)
