### ISSUE TITLE
Radial dial thumb not visible

### ISSUE THREAD

**Issue by jamescadd** [bbbenji/synthwave-hass#33]
![image](https://user-images.githubusercontent.com/2729218/83767011-f1e2c380-a631-11ea-9193-e1c6725b65c5.png)

Great theme but one small issue - I'm not able to see the thumb on radial sliders very well.  I believe I have the extras installed correctly, installed them through HACS and used the below in configuration.yaml.  I do see the color radiant stripe at the top left of the UI under "Home Assistant".

    - url: /hacsfiles/synthwave-hass-extras/synthwave-hass-extras.js
      type: js

**Comment by bbbenji** [comment]
Yep, it sounds like you have the extras installed and working. Latest HA updates have started to break this theme. When I find some free time I will try to begin resolving them. Thanks for the report.

**Comment by yinyanghu** [comment]
+1 Same issue for some hyperlinks in Logbook. They are invisible right now.
