### ISSUE TITLE
Ha-user-badge icon

### ISSUE THREAD

**Issue by hashtagrik** [bbbenji/synthwave-hass#38]
Hi first of all love the style of the theme great job! 

But one issue I found was that the round initial icon of the ha-user-badge isn't shown. 
Couldn't figure out how to change it since I am new to this. 

Again love the theme would like to see the updates on this 👍

**Comment by bbbenji** [comment]
@hashtagrik I'm sorry, I no longer develop this theme. But happy to take PR's. I hope you find a solution and please share if you do!

I will be leaving this issue open until resolved.

**Comment by hashtagrik** [comment]
After writing I saw it was no longer under maintenance. Will look into it see if I can find the sollution :)

**Comment by bbbenji** [comment]
@hashtagrik please update and let me know if your issues are resolved.

**Comment by bbbenji** [comment]
Confirmed as visible. The background of the initials itself is not, however. That's fine, I prefer it that way.
