### ISSUE TITLE
HACS cards unreadable

### ISSUE THREAD

**Issue by atomicpapa** [bbbenji/synthwave-hass#7]
Cards in HACS are blank white boxes

![Screenshot_20190815-092836](https://user-images.githubusercontent.com/6396499/63101873-97ac3100-bf3f-11e9-96ab-393e38b144f5.png)

Screenshot is from mobile but is the same in my laptop

**Comment by atomicpapa** [comment]
Aside from this, all cards are fine

**Comment by bbbenji** [comment]
Update. It was just fixed via f940406964f095badc8f50c5481c4a2534373173
